# GitHub Copilot Setup Steps for ship-it repository
# This file describes how to set up the development environment

setup_steps:
  # Step 1: Check Node.js installation
  - description: "Verify Node.js is installed"
    command: "node --version"
    
  # Step 2: Check npm installation  
  - description: "Verify npm is installed"
    command: "npm --version"
    
  # Step 3: Install dependencies (if package.json exists)
  - description: "Install project dependencies"
    command: "[ -f package.json ] && npm install || echo 'No package.json found, skipping npm install'"
    
  # Step 4: Run linting (if configured)
  - description: "Run linting checks"
    command: "[ -f package.json ] && npm run lint 2>/dev/null || echo 'No lint script configured'"
    
  # Step 5: Run tests (if configured)
  - description: "Run tests"
    command: "[ -f package.json ] && npm test 2>/dev/null || echo 'No test script configured'"
    
  # Step 6: Run build (if configured)
  - description: "Build the project"
    command: "[ -f package.json ] && npm run build 2>/dev/null || echo 'No build script configured'"

notes:
  - "This is a minimal repository setup"
  - "Steps are conditional based on project configuration"
  - "Add more specific steps as the project grows"
